baseURL = "https://raditian-hugo.radity.com/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Overview"
  URL = "#overview"
  weight = 2

 [[menu.header]]
  name = "Workshops"
  URL = "#workshops"
  weight = 2

  [[menu.header]]
  name = "Program"
  URL = "#program"
  weight = 3

  [[menu.header]]
  name = "Information"
  URL = "#information"
  weight = 4

  [[menu.header]]
  name = "Registration"
  URL = "#registration"
  weight = 5

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 6


  [[menu.footer]]
  name = "Overview"
  URL = "#overview"
  weight = 2

  [[menu.footer]]
  name = "Program"
  URL = "#program"
  weight = 3

  [[menu.footer]]
  name = "Registration"
  URL = "#registration"
  weight = 4


[params]

  sections = ["showcase", "overview", "workshops" "program", "information", "registration", "contact"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    image = "img/logo.svg"

  [params.footer]
      copyright = "© Pestilli Lab. All rights reserved."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
